language: python

env:
  - PYWIKIBOT_NO_USER_CONFIG=2

before_install:
  - git clone https://github.com/wikimedia/pywikibot pywikibot-build
  - mkdir -p pywikibot-build/scripts/i18n
  - touch pywikibot-build/scripts/i18n/__init__.py
  - for item in *; do if [[ -d "$item" ]]; then cp -rp "$item" pywikibot-build/scripts/i18n; fi; done

install:
  - pip install six nose requests

script:
  - cd pywikibot-build
  - nosetests --verbosity=2 tests.l10n_tests

notifications:
  email:
    recipients:
      - pywikibot-commits@lists.wikimedia.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#pywikibot"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
